# A simple Hello World

name: Hello World

on: [push|pull_request]

jobs:
  Say-Something:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello There!!!! Some new changes have been made. Now run on pr and push"
